services:
  # Servicio de Chrome sin cabeza (Browserless)
  chrome:
    image: browserless/chrome:latest
    restart: unless-stopped
    ports:
      - "3002:3000" # Puerto para acceder a la interfaz de depuración
    environment:
      # Configuración de Browserless
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=300000
      - MAX_QUEUE_LENGTH=20
      - PREBOOT_CHROME=true
      - ENABLE_DEBUGGER=true # Necesario para habilitar el depurador
      - ENABLE_DEBUG_VIEWER=true # Habilitar el visor de depuración
      - WORKSPACE_DELETE_EXPIRED=true
      - WORKSPACE_EXPIRE_DAYS=7
      - ENABLE_CORS=true
      - DEBUG=browserless*,puppeteer:* # Logs de depuración detallados
      - FUNCTION_ENABLE_INCOGNITO_MODE=true
      - TOKEN=S0G1V9NnysIfNo6b4594f2f03360c5cb9faececf54
      - CHROME_REFRESH_TIME=10000 # Actualiza el estado del navegador cada 10s
      - KEEP_ALIVE=true # Mantiene las sesiones activas
      - DEFAULT_LAUNCH_ARGS=["--window-size=1920,1080", "--disable-features=IsolateOrigins", "--disable-site-isolation-trials"]
    shm_size: 2gb
    mem_limit: 4g

  # Servicio de scraper
  scraper:
    build: .
    ports:
      - "3001:3000" # Expone la API en el puerto 3001
    environment:
      - PORT=3000 # Puerto interno donde escucha tu aplicación
      # URL de Browserless para conectarse (nombre del servicio + puerto interno)
      - BROWSERLESS_URL=ws://chrome:3000?token=S0G1V9NnysIfNo6b4594f2f03360c5cb9faececf54
      - BROWSERLESS_TOKEN=S0G1V9NnysIfNo6b4594f2f03360c5cb9faececf54 # Token de autenticación
    restart: unless-stopped
    # Esto permite a ambos contenedores encontrarse en la misma red
    depends_on:
      - chrome
    volumes:
      - ./:/app # Monta el directorio raíz del proyecto
      - /app/node_modules # Evita que node_modules local sobrescriba
      - ./logs:/app/logs # Para logs
